---
- hosts: all
  become: yes
  roles:
    - common

- hosts: etcd
  become: yes
  roles:
    - etcd

- hosts: postgres
  become: yes
  roles:
    - patroni

- hosts: haproxy
  become: yes
  roles:
    - haproxy
    - pgbouncer

- hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana
