all:
  vars:
    ansible_user: jakir
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:

    etcd:
      hosts:
        etcd1-server:
          ansible_host: 192.168.1.111
        etcd2-server:
          ansible_host: 192.168.1.112
        # Recommended: add third node
        # etcd3-server:
        #   ansible_host: 192.168.1.118

    postgres:
      children:
        primary:
          hosts:
            pg1-server:
              ansible_host: 192.168.1.113

        replica:
          hosts:
            pg2-server:
              ansible_host: 192.168.1.114

    haproxy:
      hosts:
        lb1-server:
          ansible_host: 192.168.1.115

    monitoring:
      hosts:
        prometheus-server:
          ansible_host: 192.168.1.116
        grafana-server:
          ansible_host: 192.168.1.117
