# group_vars/etcd.yml
etcd_packages:
  - etcd
  - etcd-client

# Default etcd configuration (safe defaults)
etcd_name: "etcd-server"
etcd_data_dir: "/var/lib/etcd"
etcd_enable_v2: true

# Multi-node cluster
etcd_initial_cluster:
  - "etcd1-server=http://192.168.1.111:2380"
  - "etcd2-server=http://192.168.1.112:2380"
  - "etcd3-server=http://192.168.1.113:2380"

# UFW / firewall rules (optional)
etcd_ports:
  - 2379
  - 2380

etcd_allowed_ips:
  - { ip: '192.168.1.111', ports: [2379, 2380] }
  - { ip: '192.168.1.112', ports: [2379, 2380] }
  - { ip: '192.168.1.113', ports: [2379, 2380] }
