---
- name: Setup common tools on all servers
  hosts: all
  become: yes
  roles:
    - common
- name: Show installed common packages
  hosts: all
  become: yes
  tasks:
    - name: Debug installed packages
      command: "{{ item }} --version"
      loop:
        - wget
        - curl
        - tar
        - zip
      register: version_output
      changed_when: false

    - name: Show package versions
      debug:
        var: version_output.results
