all:
  vars:
    ansible_user: jakir
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:

    etcd:
      hosts:
        etcd1-server:
          ansible_host: 192.168.1.111
        etcd2-server:
          ansible_host: 192.168.1.112
        etcd3-server:
          ansible_host: 192.168.1.113

    postgres:
      children:
        primary:
          hosts:
            postgre1-server:
              ansible_host: 192.168.1.114

        replica:
          hosts:
            postgre2-server:
              ansible_host: 192.168.1.115
            postgre3-server:
              ansible_host: 192.168.1.116

    haproxy:
      hosts:
        lb-server:
          ansible_host: 192.168.1.117

    monitoring:
      hosts:
        prometheus-server:
          ansible_host: 192.168.1.118
        grafana-server:
          ansible_host: 192.168.1.119
