all:
  children:
    etcd:
      hosts:
        node1: { ansible_host: 192.168.1.117 }
        node2: { ansible_host: 192.168.1.118 }
        node3: { ansible_host: 192.168.1.119 }
    postgres:
      hosts:
        pg1: { ansible_host: 192.168.1.120 }
        pg2: { ansible_host: 192.168.1.121 }
        pg3: { ansible_host: 192.168.1.122 }
    haproxy:
      hosts:
        lb: { ansible_host: 192.168.1.123 }
    monitoring:
      hosts:
        prometheus: { ansible_host: 192.168.1.124 }
        grafana: { ansible_host: 192.168.1.125 }
